### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by sholtomaud** [flyfir248/Microsoft-Phi-2#1]
none of the doco is right and it does work.

**Comment by flyfir248** [comment]
### Interactive Colab Notebook

I've made an attempt to integrate the Colab notebook directly into this README. Please give it a try by clicking this gist link : (https://gist.github.com/flyfir248/d54f46ab6dd1f1c30e6585b0e77e973e). Admittedly, it's been a bit of a journey to get it right, and I appreciate your patience.

If you encounter any difficulties or have suggestions for improvement, I'm all ears. Let's make this collaboration as smooth as possible! 🙏


Feel free to reach out if you have any questions or encounter any issues. Happy coding! 🚀


> none of the doco is right and it does work.
